apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: application
spec:
  selector:
    app: application
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30009
    targetPort: 8000

