apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      name: django-deployment
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: rakhemanohar/app:django
        ports:
        - containerPort: 80
